{"issue_type": "request_error", "error_msg": "HTTPConnectionPool(host='ci.bristol.ct.us', port=80): Max retries exceeded with url: /robots.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f14170d6310>, 'Connection to ci.bristol.ct.us timed out. (connect timeout=15)'))"}