{"issue_type": "request_error", "error_msg": "HTTPConnectionPool(host='ci.marina.ca.us', port=80): Max retries exceeded with url: /robots.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f029d417e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}