{"issue_type": "request_error", "error_msg": "HTTPConnectionPool(host='cityofelberton.net', port=80): Max retries exceeded with url: /robots.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f345ec98430>, 'Connection to cityofelberton.net timed out. (connect timeout=15)'))"}