{"issue_type": "request_error", "error_msg": "HTTPConnectionPool(host='co.cumberland.nj.us', port=80): Max retries exceeded with url: /robots.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f578d67e3d0>, 'Connection to co.cumberland.nj.us timed out. (connect timeout=15)'))"}