{"issue_type": "request_error", "error_msg": "HTTPConnectionPool(host='co.rice.mn.us', port=80): Max retries exceeded with url: /robots.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa25d033760>, 'Connection to co.rice.mn.us timed out. (connect timeout=15)'))"}