{"issue_type": "request_error", "error_msg": "HTTPConnectionPool(host='co.saint-croix.wi.us', port=80): Max retries exceeded with url: /robots.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1d26969d90>: Failed to establish a new connection: [Errno 111] Connection refused'))"}