{"issue_type": "request_error", "error_msg": "HTTPConnectionPool(host='heidelbergborough.com', port=80): Max retries exceeded with url: /robots.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd819a97340>, 'Connection to heidelbergborough.com timed out. (connect timeout=15)'))"}