{"issue_type": "request_error", "error_msg": "HTTPConnectionPool(host='lisbonnd.com', port=80): Max retries exceeded with url: /robots.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f04181aa100>, 'Connection to lisbonnd.com timed out. (connect timeout=15)'))"}