{"issue_type": "request_error", "error_msg": "HTTPSConnectionPool(host='vergennes.org', port=443): Max retries exceeded with url: /robots.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f39a3f30520>, 'Connection to vergennes.org timed out. (connect timeout=15)'))"}