{"issue_type": "request_error", "error_msg": "HTTPConnectionPool(host='cityofalgoodtn.gov', port=80): Max retries exceeded with url: /robots.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d5c363190>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}