{"issue_type": "request_error", "error_msg": "HTTPSConnectionPool(host='milanohio.gov', port=443): Max retries exceeded with url: /robots.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7b9dc4b040>, 'Connection to milanohio.gov timed out. (connect timeout=15)'))"}